version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_innovatech
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: innovatech_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    networks:
      - innovatech-network
    volumes:
      - db_data:/var/lib/mysql 


  backend-ventas:
    image: ferxys/innovatech-ventas:latest
    container_name: api_ventas
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - innovatech-network

  
  backend-despachos:
    image: ferxys/innovatech-despachos:latest
    container_name: api_despachos
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - innovatech-network

 
  frontend:
    image: ferxys/innovatech-frontend:latest
    container_name: app_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - innovatech-network

networks:
  innovatech-network:
    driver: bridge

volumes:
  db_data: