version: '3.8'

services:
  # 1. Base de Datos (Cumple con la instancia "Data" que pedía el EP1)
  db:
    image: mysql:8.0
    container_name: db_innovatech
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: innovatech_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    networks:
      - innovatech-network
    volumes:
      - db_data:/var/lib/mysql # <-- ¡Punto clave para la rúbrica! Persistencia de datos mediante Named Volume

  # 2. Microservicio de Ventas
  backend-ventas:
    build: 
      context: ./Backend/back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: api_ventas
    restart: always
    ports:
      - "8081:8080" # Lo exponemos en el 8081 de tu PC/EC2 para que no choque con el otro
    depends_on:
      - db
    networks:
      - innovatech-network
  # 3. Microservicio de Despachos
  backend-despachos:
    build: 
      context: ./Backend/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: api_despachos
    restart: always
    ports:
      - "8082:8080" # Lo exponemos en el puerto 8082
    depends_on:
      - db
    networks:
      - innovatech-network

  # 4. Frontend en React
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: always
    ports:
      - "80:80" # El Front es el único expuesto al puerto 80 (Internet)
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - innovatech-network

# Configuración de la red interna
networks:
  innovatech-network:
    driver: bridge

# Configuración del volumen persistente
volumes:
  db_data: